#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
  path: /
  defaults: { _controller: 'App\Controller\WelcomeController::index' }
product-details:
  path: /details/{id}
  defaults: { _controller: 'App\Controller\DetailsProduitController::index' }


